import localFont from "next/font/local";
import "./globals.css";



export const metadata = {
  title: "MERN website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  style={{ "--primary-color": "#262626" }}>
        {children}
      </body>
    </html>
  );
}
